### ISSUE TITLE
Support mocha@10

### ISSUE THREAD

**Issue by nidibm** [juhovh/mocha-jenkins-reporter#101]
Please add support for mocha@10

Getting error `peer dep missing: mocha@^5.2.0 || ^6.0 || ^7.0 || ^8.0 || ^9.0, required by mocha-jenkins-reporter@0.4.7`

**Comment by apupier** [comment]
there is this PR which was provided https://github.com/juhovh/mocha-jenkins-reporter/pull/103

**Comment by juhovh** [comment]
Should be fixed in the 0.4.8 release now, let me know if there's any issues.
