### ISSUE TITLE
Mocha hangs on startup if report location references a non-existent folder

### ISSUE THREAD

**Issue by danopia** [juhovh/mocha-jenkins-reporter#22]
For example, `build/test-results/` where test-results doesn't exist, or `build/results.xml` where build doesn't exist. For some reason this seems to silent-halt mocha while it's starting up. Perhaps an error is being eaten somewhere?

**Comment by juhovh** [comment]
Hi, thank you for reporting. Could you please check the current master (not released yet) if it fixes this issue. It always interprets the non-existing directory as a file, but that could be improved I guess if it is necessary. At least it shouldn't fail silently any more.

**Comment by charleswhchan** [comment]
+1 would like to see a new release with this fix.

**Comment by jvah** [comment]
@charleswhchan Thank you for reminding me, this was left hanging since there was no reply and I simply forgot. 0.1.9 release is now out and I tested it to work quite well on local machine.

**Comment by charleswhchan** [comment]
@jvah Thanks for the release! I updated my dependencies and it works. Cheers.
