### ISSUE TITLE
Setting the reporter options when not using Make

### ISSUE THREAD

**Issue by satyamiit** [juhovh/mocha-jenkins-reporter#23]
Hi,

This is a question, rather than an issue. I could not find a better way to get an answer for this, sorry.

How do I set the junit_report_path when I am running mocha from the command line? This is what have so far:
mocha --recursive --reporter mocha-jenkins-reporter 

With the above command, I do see that my tests all run fine and console results look fine. But I do not see any xml file in my folder (probably because I did not set the junit_report_path). Could you please tell me how to set this when I am running from command line?

Thanks
Satya

**Comment by juhovh** [comment]
It's the same as with make, try adding just "JUNIT_REPORT_PATH=report.xml" without the @ character to the beginning of your command line and it should work. Let me know if this helped.

**Comment by satyamiit** [comment]
That worked, Thanks! I did not realize these variables are for Jenkins and was trying for a way to set them when running on command line. Anyways, it woks now, thank you!
