### ISSUE TITLE
Using with Grunt

### ISSUE THREAD

**Issue by bagofjuice** [juhovh/mocha-jenkins-reporter#24]
Hi, how can I pass the reporterOptions to use with Grunt?

Currently I'm using something like this in my Gruntfile (using the [grunt-mocha-test](https://github.com/pghalliday/grunt-mocha-test) module):

            reportUnit: {
                options: {
                    reporter: 'xunit',
                    quiet: true,
                    captureFile: 'report.xml'
                },
                src: ['server/**/*.spec.js']
            }

but would like to change it to:

            reportUnit: {
                options: {
                    reporter: 'mocha-jenkins-reporter',
                    reporterOptions: {
						junit_report_name: "test",
						junit_report_path: "report.xml",
						junit_report_stack: 1
					}
                },
                src: ['server/**/*.spec.js']
            }

however, reporterOptions is not being picked up.

**Comment by juhovh** [comment]
I think this is more of a grunt and mocha issue than reporter issue, I have no idea.
