### ISSUE TITLE
Messes with the filtering options

### ISSUE THREAD

**Issue by fatso83** [juhovh/mocha-jenkins-reporter#25]
I am not sure why, but choosing this reporter instead of any other will make filtering tests fail. 

For instance, doing
`./node_modules/.bin/mocha --recursive  --invert --grep ^slow. --reporter xunit spec`
will run all non-slow tests in my suites.

Substituting xunit for your reporter will suddenly run *all* tests
`./node_modules/.bin/mocha --recursive  --invert --grep ^slow. --reporter mocha-junit-reporter spec`

**Comment by juhovh** [comment]
Can you say which mocha version are you using? I have used the filtering with this reporter a lot, so it sounds weird that it is breaking.

**Comment by fatso83** [comment]
```
$ pick_json devDependencies.mocha < package.json
^2.1.0
```

**Comment by fatso83** [comment]
Also tested with `2.3.4` just now.

Versions:
```
$ node --version
v5.3.0

$ npm --version
3.3.12
```

**Comment by jvah** [comment]
Uhm, I just realised you are using `mocha-junit-reporter`, that is not my reporter. This is an invalid bug report.
