### ISSUE TITLE
How to get the testname to show up in slack summary

### ISSUE THREAD

**Issue by prolificcoder** [juhovh/mocha-jenkins-reporter#26]
Hello, this plugin has been great for us and we currently were able to get the test summary nicely into slack
![image](https://cloud.githubusercontent.com/assets/149176/12338127/f3a92ea2-bac2-11e5-9045-b543b5100cdb.png)

I am wondering how to get the test name into the summary as well? The report generated reports.xml has the test name info but not the slack summary. Is it something that jenkins-slack plugin has to do?

**Comment by juhovh** [comment]
To be honest I have no idea about slack since I have never used it, I'm closing this issue since no one else has replied either.
