### ISSUE TITLE
An invalid XML character (Unicode: 0x1b) was found in the CDATA section

### ISSUE THREAD

**Issue by aaronbriel** [juhovh/mocha-jenkins-reporter#34]
I'm running into an issue with this change implemented in PR #32. Jenkins fails to parse the XML file with the following failure:
"An invalid XML character (Unicode: 0x1b) was found in the CDATA section. Nested exception: An invalid XML character (Unicode: 0x1b) was found in the CDATA section."

Is there a way to wrap the CDATA output in a function that strips out this character (and other possible ones that cannot be parsed)?

**Comment by juhovh** [comment]
Excellent point, just as a note to self the following characters are valid:

**Comment by juhovh** [comment]
@aaronbriel please check if the latest master fixes your issue

**Comment by aaronbriel** [comment]
Any way you can accept #33 first? :)  I have some jenkins jobs wired up to my forked repo which are expecting the screenshots...

**Comment by aaronbriel** [comment]
This still appears to be causing a failure due to the system-out closing tag for CDATA not being written:

Failed to read test report file /Users/qa-administrator/jenkins/workspace/dadada/test-results/dadadada.xml
org.dom4j.DocumentException: Error on line 334 of document file:///Users/qa-administrator/jenkins/workspace/dadada/test-results/dadadada.xml : XML document structures must start and end within the same entity. Nested exception: XML document structures must start and end within the same entity.
	at org.dom4j.io.SAXReader.read(SAXReader.java:482)
	at org.dom4j.io.SAXReader.read(SAXReader.java:264)
	at hudson.tasks.junit.SuiteResult.parse(SuiteResult.java:123)
	at hudson.tasks.junit.TestResult.parse(TestResult.java:282)
	at hudson.tasks.junit.TestResult.parsePossiblyEmpty(TestResult.java:228)
	at hudson.tasks.junit.TestResult.parse(TestResult.java:163)
	at hudson.tasks.junit.TestResult.parse(TestResult.java:146)
	at hudson.tasks.junit.TestResult.<init>(TestResult.java:122)
	at hudson.tasks.junit.JUnitParser$ParseResultCallable.invoke(JUnitParser.java:119)
	at hudson.tasks.junit.JUnitParser$ParseResultCallable.invoke(JUnitParser.java:93)
	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:2720)
	at hudson.remoting.UserRequest.perform(UserRequest.java:121)
	at hudson.remoting.UserRequest.perform(UserRequest.java:49)
	at hudson.remoting.Request$2.run(Request.java:326)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at hudson.remoting.Engine$1$1.run(Engine.java:69)
	at java.lang.Thread.run(Thread.java:745)

**Comment by jvah** [comment]
I'm a bit puzzled about what is causing this, is it possible that you have a CDATA section or otherwise a `]]>` string in your console output?

**Comment by juhovh** [comment]
Actually the original fix had a problem, please try again now... And I should still probably somehow handle the CDATA closing section inside system-out, but that's not very likely to happen.

**Comment by aaronbriel** [comment]
This is resolved with your latest fix, and also works with my changes for #33.  I've merged these fixes with that branch and pushed to my master branch at (https://github.com/aaronbriel/mocha-jenkins-reporter/).

**Comment by aaronbriel** [comment]
This appears to be working for me now, with my changes incorporated into your new master branch.

**Comment by aaronbriel** [comment]
@juhovh I've merged your latest master with my master branch (https://github.com/aaronbriel/mocha-jenkins-reporter) and I'm no longer seeing this issue.  Thanks!

**Comment by sgtcoolguy** [comment]
This should be re-opened. This commit seems to have re-introduced the issue: https://github.com/juhovh/mocha-jenkins-reporter/commit/9d9fca12d12c6b8dfa504c065ed413e2c7202251

**Comment by juhovh** [comment]
Sigh, I've fixed at least 3 bug reports that came as a result of 9d9fca1 and already regret merging it. Could @palmerj3 be kind and take the ball on this one? :)

**Comment by palmerj3** [comment]
@juhovh do you have a reproducible test case that should pass but doesn't? If so I'm happy to take a look!

One thing that would likely help immensely is, instead of putting the failure message in <failure message="foo"> put it in <failure message="">foo</failure>.

I've done this recently in jest-junit. https://github.com/palmerj3/jest-junit/commit/3f4780e59558273325c15c92a5eaebdcae0651a2

**Comment by palmerj3** [comment]
@juhovh if you or anyone has a test that outputs invalid XML please try it out with this PR https://github.com/juhovh/mocha-jenkins-reporter/pull/68

**Comment by palmerj3** [comment]
@sgtcoolguy mind taking a look at my PR mentioned above?

**Comment by jvah** [comment]
Unfortunately I don't have a test case at hand, but I don't see how PR #68 is related at all? We're talking about the console.log output and you are sanitising the diff which is completely not related.

Also the whole strip-ansi module code is another thing, https://github.com/chalk/strip-ansi/blob/master/index.js depending on https://github.com/chalk/ansi-regex/blob/master/index.js is a prime example of what's wrong with npm modules... I think I'll just take back my own code that filtered the invalid characters and commit it there.

**Comment by jvah** [comment]
I pushed a suggested fix to master, see #63

**Comment by alexisreina** [comment]
Hello @jvah, did you updated the package version?

**Comment by jvah** [comment]
There has been no comments in #63 so I have therefore released this change as 0.3.9, make sure everything works now.
