### ISSUE TITLE
hijacking console.log broke my test

### ISSUE THREAD

**Issue by jjmartin** [juhovh/mocha-jenkins-reporter#36]
in 0.2.0 you are hijacking console.log.

i had a test that validates that certain text was output  -  i'm using intercept-stdout , which hijacks the process.stdout.write to capture or change the text.

since you don't resend the text you are capturing back to the output - my test no longer captures the text.

**Comment by juhovh** [comment]
Hi, please check if the latest master fixes this issue.

**Comment by jjmartin** [comment]
yes... latest master fixes the broken test.   will watch for a 0.2.1 =)

**Comment by juhovh** [comment]
0.2.1 is now released and this should be fixed, thank you for your help!
