### ISSUE TITLE
Can you add options to control the console logging a bit more?

### ISSUE THREAD

**Issue by mfriess2** [juhovh/mocha-jenkins-reporter#39]
We have a lot of mocha tests (about 250 tests and raising) thus a lot of console output is generated. The output is very nice but it's simply too much and distracts a bit from the real problems, namely the actually test failures.

Could you add an option to e.g. log only failed tests on the console and/or only the summary?

**Comment by jvah** [comment]
I believe the failures are always listed in the end of the console output and failures are also marked in red... I welcome pull requests regarding this matter, but I'm not interested in investing much time to implement it myself. The 250 tests is not that huge, I've used the reporter for several thousands of tests and I think the console output worked quite ok.
