### ISSUE TITLE
No colors in Jenkins output with Mocha 2.5.3 or 3.0.0

### ISSUE THREAD

**Issue by tsvetomir-nedyalkov** [juhovh/mocha-jenkins-reporter#45]
Hi,

We have used in the past Mocha 1.20.1 with mocha-jenkins-reporter v.0.1.2 with 'Color ANSI Console Output' = true in Jenkins and all worked well. Unfortunately after an update of Mocha to 2.5.3, we have experienced a not expected side effect - the colors in the console output in Jenkins are missing. I have tried also version 0.2.3 with Mocha 2.5.3 and 3.0.0, but the colors are still missing.

Thanks in advance!

**Comment by jvah** [comment]
I'm having the same problem, but the colors are working in local console, so this has something to do with latest Jenkins. I'll look into this.

**Comment by jvah** [comment]
Actually I am not having the same problem, try adding `--colors` as an argument to mocha to enforce outputting colors, just to be sure.

**Comment by tsvetomir-nedyalkov** [comment]
Hi,

Adding --colors resolved the issue - thanks!

Greetings,
Tsvetomir

**Comment by jvah** [comment]
👍
