### ISSUE TITLE
Issue with building using "mocha": "^2.2.5"

### ISSUE THREAD

**Issue by pranaykumar2302** [juhovh/mocha-jenkins-reporter#50]
Hello, please can anyone help with me this error?

Running "mochaTest:integration" (mochaTest) task
>> Mocha exploded!
>> Error: Cannot find module '....app'
>>     at Function.Module._resolveFilename (module.js:325:15)
>>     at Function.Module._load (module.js:276:25)
>>     at Module.require (module.js:353:17)
>>     at require (internal/module.js:12:17)
>>     at Object.<anonymous> (F:/MEAN/Ecommerce/server/api/thing/thing.integration.js:3:11)
>>     at Module._compile (module.js:409:26)
>>     at normalLoader (F:\MEAN\Ecommerce\node_modules\babel-core\lib\api\register\node.js:199:5)
>>     at Object.require.extensions.(anonymous function) [as .js] (F:\MEAN\Ecommerce\node_modules\babel-core\lib\api\register\node.js:216:7)
>>     at Module.load (module.js:343:32)
>>     at Function.Module._load (module.js:300:12)
>>     at Module.require (module.js:353:17)
>>     at require (internal/module.js:12:17)
>>     at F:\MEAN\Ecommerce\node_modules\mocha\lib\mocha.js:220:27
>>     at Array.forEach (native)
>>     at Mocha.loadFiles (F:\MEAN\Ecommerce\node_modules\mocha\lib\mocha.js:217:14)
>>     at MochaWrapper.run (F:\MEAN\Ecommerce\node_modules\grunt-mocha-test\tasks\lib\MochaWrapper.js:51:15)
>>     at F:\MEAN\Ecommerce\node_modules\grunt-mocha-test\tasks\mocha-test.js:86:20
>>     at capture (F:\MEAN\Ecommerce\node_modules\grunt-mocha-test\tasks\mocha-test.js:33:5)
>>     at Object.<anonymous> (F:\MEAN\Ecommerce\node_modules\grunt-mocha-test\tasks\mocha-test.js:81:5)
>>     at Object.<anonymous> (F:\MEAN\Ecommerce\node_modules\grunt\lib\grunt\task.js:264:15)
>>     at Object.thisTask.fn (F:\MEAN\Ecommerce\node_modules\grunt\lib\grunt\task.js:82:16)
>>     at Object.task.fn (F:\MEAN\Ecommerce\node_modules\jit-grunt\lib\jit-grunt.js:122:30)
Warning: Task "mochaTest:integration" failed. Use --force to continue.

Aborted due to warnings.

**Comment by jvah** [comment]
I don't understand, I don't see mocha-jenkins-reporter anywhere in that stack trace?

**Comment by jvah** [comment]
Just go to look at file `thing.integration.js` row 3 and the `require(...)` in it and fix it to point to the right path, for example `..\..\app` is wrong but `../../app` works. And do not report bugs in your own code in this bug tracker, that is quite annoying, thank you.
