### ISSUE TITLE
zero length .xml file triggers: "TypeError: Cannot read property 'failures' of null"

### ISSUE THREAD

**Issue by markstos** [juhovh/mocha-jenkins-reporter#55]
I just got this failure today:

        TypeError: Cannot read property 'failures' of null

From what I can tell, it was triggered because the test .xml file was zero bytes long. I can also see that lots of the tests ran. When I clicked "Rebuild" in Jenkins, the build passed and the tests were processed as expected. 

What I'm guessing is that a test failed in the test suite badly enough to try to crash the process. I'm guessing that the XML contents only existed in memory at that time, so the XML output was lost, yet the `mocha-jenkins-reporter` still tried to read the zero-byte test file anyway.

If the XML file is not being written to disk periodically, could it be? That would help in the case of a test suite crash.

Also, it would still be nice to get a better diagnostic back in the case where for some reason a zero-byte test file is generated.

Thanks for helping provide a better experience for Mocha tests on Jenkins!

**Comment by markstos** [comment]
PR #52 seems to address exactly the case I'm running into-- it patches exactly the place the code where 
`TypeError: Cannot read property 'failures' of null` was being thrown. I'm going to give it a try now.

The current code assumes that if the `fail` event is emitted that the `currentSuite` variable is also defined. When `currentSuite` is not defined when `fail` is emitted, the `err` parameter passed to the `fail` event is never seen.

**Comment by juhovh** [comment]
I just released 0.3.2 which merged PR 52 and should fix this issue, please reopen if the problem continues. Thank you for your reports, they are very helpful, and sorry for the delay!
