### ISSUE TITLE
Crash on runner.on('fail') event when currentSuite is undefined

### ISSUE THREAD

**Issue by mmani-systran** [juhovh/mocha-jenkins-reporter#59]
mocha-jenkins-reporter crash v0.3.5 (latest version) when
* on runner "fail" event 
* currentSuite undefined

this is due to a commented err variable in /lib/jenkins.js
`  
runner.on('fail', function(test/*, err*/) {
    if (currentSuite == undefined) {
      // Failure occurred outside of a test suite.
      console.error(err);
`

`
if (test == undefined) {
        log(fmt, n, "unknown");
        addTestToSuite({
          title: "unknown",
          file: process.cwd() + "/other.js",
          state: 'failed',
          err: err
        });
      }
`

**Comment by INRIX-yogesh-randhawa** [comment]
Any fix for this problem?

**Comment by tolbertam** [comment]
#61 and #62 are good candidates to fix this I think.

**Comment by jvah** [comment]
Merged #61 and released it as 0.3.6, thank you all for your help.

**Comment by jvah** [comment]
Oh and sorry for the delay, I've been in China behind bad internet connections, so it has caused some trouble.
