### ISSUE TITLE
Strip invalid XML characters

### ISSUE THREAD

**Issue by toddpi314** [juhovh/mocha-jenkins-reporter#63]
__Issue__: if someone console.logs something in the wide unicode space that isn't compatible with XML spec (ex. `\x1b`), the `report.xml` generated will be invalid.

Would you accept a PR that will add a validator that maps to XML 1.0 Character Range specification?

Ref: [Extensible Markup Language (XML) 1.0 (Fifth Edition)](https://www.w3.org/TR/REC-xml/#charsets)

**Comment by jvah** [comment]
If it doesn't break anything else then I'm happy to accept a PR fixing the XML.

**Comment by sgtcoolguy** [comment]
Relates to #34

**Comment by jvah** [comment]
@sgtcoolguy @toddpi314 I have just pushed https://github.com/juhovh/mocha-jenkins-reporter/commit/9b232b8d2dffab762bb0e4acf1d3dc98d11ba14e reverting the old changes to master, could you please test it out and I'll make a new release?

**Comment by jvah** [comment]
Should be fixed now again, did not get any comments.
