### ISSUE TITLE
vulnerability in mocha 3.x

### ISSUE THREAD

**Issue by caa1211** [juhovh/mocha-jenkins-reporter#74]
Because the latest mocha in 3.x (v3.5.3) has vulnerability in dependency of grow 1.9.2
```
Mocha Vulnerability Issue:
https://github.com/mochajs/mocha/issues/2791

Mocha 3.5.3 dependency
https://github.com/mochajs/mocha/blob/v3.5.3/package.json
```

Could you please help to upgrade mocha to 4.x version or give some suggestions? thanks your contributions.

**Comment by asztal** [comment]
Presumably mocha should be a peerDependency rather than an actual dependency. `mocha-junit-reporter` does this so I assume it's not a problem.

**Comment by apupier** [comment]
Current Mocha versions supported are [5.2+](https://github.com/juhovh/mocha-jenkins-reporter/blob/4fdd7eae0121102759b97c13f83523ff3da7ade0/package.json#L26) so Mocha 3.x vulnerability is not visible

**Comment by juhovh** [comment]
Thank you for the comment, I'm closing this old ticket.
