### ISSUE TITLE
Invalid characters (Unicode: 0x1b) in the failure message

### ISSUE THREAD

**Issue by jfiala-cz** [juhovh/mocha-jenkins-reporter#85]
Similar to: https://github.com/juhovh/mocha-jenkins-reporter/issues/34

Error message in the "message" attribute of "failure" element is not sanitized and can contain invalid characters, which results in Jenkins not being able to read the file.

Found when using mocha-jenkins-reporter with Nightwatch.js.
`org.dom4j.DocumentException: Error on line 4 of document  : An invalid XML character (Unicode: 0x1b) was found in the value of attribute "message" and element is "failure". Nested exception: An invalid XML character (Unicode: 0x1b) was found in the value of attribute "message" and element is "failure".`

**Comment by bruun** [comment]
I am experiencing the same error. It can be reproduced by failing a `expect(stub).calledWithExactly(...)` using `sinon-chai`.

**Comment by juhovh** [comment]
I pushed a change that removes the invalid character with `removeInvalidXmlChars`, I checked the other attributes and it would seem that they're unlikely to have the same problem. If you can, please confirm that it fixes the issue.

**Comment by juhovh** [comment]
I published 0.4.2 that includes the change, hope it helps.

**Comment by jfiala-cz** [comment]
The issue seems to be fixed. Thanks :)
